---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package on the remote hosts
    apt:
      name: {{ apache_package }} 
      name: {{ php_package }} 
      state: latest
      update_cache: yes
      when: ansible_distribution_version == "Ubuntu"

