---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package on the remote hosts
    apt:
      name: apache2 
      name: libapache2-mod- php 
      state: latest
      update_cache: yes
      when: ansible_distribution_version == "Ubuntu"

