---

- hosts: all
  become: true
  tasks:

  - name: install updates (CentOS)
    dnf :
      update_only: yes 
      update_ cache: yes
      when: ansible_distribution == "CentOS"
      
  - name: install updates (Ubuntu)
    dnf :
      update_only: yes 
      update_ cache: yes
      when: ansible_distribution == "Ubuntu"
      
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package on the remote hosts
    package:
      name: {{ apache_package }} 
      name: {{ php_package }} 
      state: latest
      update_cache: yes

  - name: copy default html file for site 
    tags: apache, apache2, httpd
    сору:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root 
      group: root 
      mode: 0644

- hosts: db_servers become: true tasks:
  - name: install mariadb package (CentoS)
    tags: db,sql,mariadb,database
    dnf :
      name: mariadb state: latest
      when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
      when: ansible_distribution == "Ubuntu"


- hosts: workstations 
  become: true 
  tasks:
  - name: install the package unzip 
    package:
      name: unzip

  - name: download, unzip terraform 
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /usr/local/bin
    remote_ src: yes 
    mode: 0755
    owner: root 
    group: root

  - name: start httpd (Centos) 
  tags: apache, centos, httpd 
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"|


